name: Django GitHub Actions
run-name: Deploy by @${{ github.actor }}
on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubunti-latest
        strategy:
            max-parallel: 1
            matrix:
                python-version: [3.12.2]
        
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python Version ${{ matrix.python-version}}
              uses: actions/setup-python@v3
              with:
                python-version: ${ matriz.python-version }} 
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                flake8 .

