name: Django GitHub Actions
run-name: Deploy by @${{ github.actor }}
on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            matrix:
                python-version: [3.12.2]
        
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up Python Version ${{ matrix.python-version}}
              uses: actions/setup-python@v5.0.0
              with:
                python-version: ${{ matrix.python-version }} 
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                flake8 .
            - name: Running the tests
              run: |
                python manage.py test
    deploy:
      runs-on: ubuntu-latest
      name: Deploy da aplicação Django no Heroku
      steps:
        - name: checkout       
          uses: actions/checkout@v4.1.1
          
        - name: Deploy
          uses: akhileshNS/heroku-deploy@v3.13.15
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
            heroku_email: "2106474@aluno.univesp.br"
            branch: main  

